export const NotificationType = {
  BOOKING_CREATED: "BOOKING_CREATED",
  PAYMENT_SUBMITTED: "PAYMENT_SUBMITTED",
  NEW_RESERVATION: "NEW_RESERVATION",
  BOOKING_CONFIRMED: "BOOKING_CONFIRMED",
  BOOKING_REJECTED: "BOOKING_REJECTED",
  BOOKING_CANCELLED: "BOOKING_CANCELLED",
  CUSTOMER_CANCELLED: "CUSTOMER_CANCELLED",
  BOOKING_EXPIRED: "BOOKING_EXPIRED",
  BOOKING_REMINDER: "BOOKING_REMINDER",
  REVIEW_INVITE: "REVIEW_INVITE",
} as const;

export type NotificationTypeValue =
  (typeof NotificationType)[keyof typeof NotificationType];
